### PR TITLE
iocage jail for FreeNAS

### PR DESCRIPTION
**Pull request by tprelog**
ok 2nd try, I think I have it together now.
 I'm running TasmoAdmin from an iocage jail on my FreeNAS server using nginx and php72.

A basic guide is in the REAME. Please consider this to help others do the same.

At this time the links are pointing to my repo but should you find this acceptable to merge those can be easily edited

Thanks!

### CODE REVIEW

**Comment by reloxx13** [comment]
@RaymondMouthaan guess this changes should not affect the docker build.

maybe exclude the .iocage folder

**Comment by reloxx13** [comment]
@RaymondMouthaan 

```
# Setup application
COPY tasmoadmin /var/www/tasmoadmin
RUN find /var/www/tasmoadmin -type f -name ".htaccess" -depth -exec rm -f {} \; \
    && find /var/www/tasmoadmin -type f -name ".empty" -depth -exec rm -f {} \; \
    && rm -rf /var/www/tasmoadmin/.iocage
```

is this correct (last line) ?

**Comment by RaymondMouthaan** [comment]
@reloxx13, looking from my iPhone, yes that last line should work to remove the .iocage folder

**Comment by RaymondMouthaan** [comment]
Does it require a new release especially for freenas?

**Pull request merged**
